#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend www-backend\n\nbackend www-backend\n\tbalance roundrobin\n\tserver 128085-web-01 100.26.209.99:80 check\n\tserver 128085-web-02 52.3.250.26:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
